# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [2]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
import gmaps

# Import API key
from api_keys import geoapify_key

In [3]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,faya,18.3851,42.4509,22.06,35,21,2.60,SA,1666108228
1,1,farsund,58.0948,6.8047,13.30,100,0,7.65,NO,1666108228
2,2,new norfolk,-42.7826,147.0587,11.72,58,12,1.34,AU,1666108230
3,3,jamestown,42.0970,-79.2353,5.77,77,100,9.77,US,1666107934
4,4,lanzhou,36.0564,103.7922,14.53,48,59,1.20,CN,1666108230

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [4]:
#%%capture --no-display

# Configure the map plot
locations = city_data_df[["Lat", "Lng"]]
weights = city_data_df['Humidity']
fig = gmaps.figure(center=(20.0, 0.0), zoom_level=2)
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))


# Display the map
fig

Figure(layout=FigureLayout(height='420px'))

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [5]:
# Narrow down cities that fit criteria and drop any results with null values
city_name = []


for index, row in city_data_df.iterrows():
    if row["Cloudiness"] == 0:
        if row ["Wind Speed"] < 10:
            if row["Max Temp"] >21 and row["Max Temp"]<27:
                city_name.append(row)

city_weather_df = pd.DataFrame(city_name)



# Drop any rows with null values
city_weather_df.dropna()

# Display sample data
city_weather_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
9,9,saint-pierre,-21.3393,55.4781,22.82,68,0,5.14,RE,1666108236
45,45,kapaa,22.0752,-159.3190,22.99,84,0,3.60,US,1666108257
51,51,hilo,19.7297,-155.0900,26.27,83,0,2.57,US,1666108260
63,63,banda,25.4833,80.3333,24.62,52,0,2.68,IN,1666108268
73,73,nalut,30.3333,10.8500,25.41,27,0,5.11,LY,1666108275
81,81,makakilo city,21.3469,-158.0858,21.66,81,0,2.57,US,1666108282
146,146,puerto del rosario,28.5004,-13.8627,24.86,73,0,4.63,ES,1666108035
152,152,kahului,20.8947,-156.4700,23.80,60,0,3.09,US,1666108246
197,197,gat,31.6100,34.7642,24.38,100,0,3.69,IL,1666108356
211,211,laguna,38.4210,-121.4238,21.67,79,0,2.06,US,1666108364
240,240,tikaitnagar,26.9500,81.5833,23.56,59,0,0.35,IN,1666108378
258,258,comodoro rivadavia,-45.8667,-67.5000,25.92,24,0,7.20,AR,1666108389
265,265,san quintin,30.4833,-115.9500,21.20,74,0,1.37,MX,1666108394
340,340,santa rosalia,27.3167,-112.2833,24.62,56,0,0.74,MX,1666108436
356,356,pemba,-12.9740,40.5178,25.03,76,0,6.33,MZ,1666108444
363,363,narwar,25.6500,77.9000,22.35,55,0,1.29,IN,1666108449
375,375,port hedland,-20.3167,118.5667,21.03,73,0,3.09,AU,1666108455
381,381,roebourne,-20.7833,117.1333,23.48,65,0,2.95,AU,1666108458
391,391,saint-francois,46.4154,3.9054,23.69,57,0,4.12,FR,1666108465
409,409,capoterra,39.1763,8.9718,24.84,71,0,3.60,IT,1666108477
421,421,stolac,43.0844,17.9575,24.88,68,0,0.80,BA,1666108483
516,516,guerrero negro,27.9769,-114.0611,23.17,68,0,0.89,MX,1666108537
517,517,bandarbeyla,9.4942,50.8122,25.88,81,0,5.14,SO,1666108537

### Step 3: Create a new DataFrame called `hotel_df`.

In [7]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity
base_url = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input="
input = "Hotel"
hotel_df = city_weather_df.copy()

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API

hotel_df["Hotel Name"] = ''

# Display sample data
hotel_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
9,9,saint-pierre,-21.3393,55.4781,22.82,68,0,5.14,RE,1666108236,
45,45,kapaa,22.0752,-159.3190,22.99,84,0,3.60,US,1666108257,
51,51,hilo,19.7297,-155.0900,26.27,83,0,2.57,US,1666108260,
63,63,banda,25.4833,80.3333,24.62,52,0,2.68,IN,1666108268,
73,73,nalut,30.3333,10.8500,25.41,27,0,5.11,LY,1666108275,
81,81,makakilo city,21.3469,-158.0858,21.66,81,0,2.57,US,1666108282,
146,146,puerto del rosario,28.5004,-13.8627,24.86,73,0,4.63,ES,1666108035,
152,152,kahului,20.8947,-156.4700,23.80,60,0,3.09,US,1666108246,
197,197,gat,31.6100,34.7642,24.38,100,0,3.69,IL,1666108356,
211,211,laguna,38.4210,-121.4238,21.67,79,0,2.06,US,1666108364,
240,240,tikaitnagar,26.9500,81.5833,23.56,59,0,0.35,IN,1666108378,
258,258,comodoro rivadavia,-45.8667,-67.5000,25.92,24,0,7.20,AR,1666108389,
265,265,san quintin,30.4833,-115.9500,21.20,74,0,1.37,MX,1666108394,
340,340,santa rosalia,27.3167,-112.2833,24.62,56,0,0.74,MX,1666108436,
356,356,pemba,-12.9740,40.5178,25.03,76,0,6.33,MZ,1666108444,
363,363,narwar,25.6500,77.9000,22.35,55,0,1.29,IN,1666108449,
375,375,port hedland,-20.3167,118.5667,21.03,73,0,3.09,AU,1666108455,
381,381,roebourne,-20.7833,117.1333,23.48,65,0,2.95,AU,1666108458,
391,391,saint-francois,46.4154,3.9054,23.69,57,0,4.12,FR,1666108465,
409,409,capoterra,39.1763,8.9718,24.84,71,0,3.60,IT,1666108477,
421,421,stolac,43.0844,17.9575,24.88,68,0,0.80,BA,1666108483,
516,516,guerrero negro,27.9769,-114.0611,23.17,68,0,0.89,MX,1666108537,
517,517,bandarbeyla,9.4942,50.8122,25.88,81,0,5.14,SO,1666108537,

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [8]:
# Set parameters to search for a hotel
radius = 10000
params = {
    
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():
    lat=row["Lat"]
    lng=row["Lng"]
    
    # Add filter and bias parameters with the current city's latitude and longitude to the params dictionary
    params["filter"] = lat
    params["bias"] = lng
    
    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"


    # Make and API request using the params dictionaty
    target_url = (f"{base_url}{input}&key={geoapify_key}&inputtype=textquery&fields=name,formatted_address&locationbias=circle:{radius}@{lat},{lng}")
    
    response = requests.get(target_url)
    
    # Convert the API response to JSON format
    name_address = response.json()
    
    
    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["features"][0]["properties"]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"
        
    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df

Starting hotel search
saint-pierre - nearest hotel: No hotel found
kapaa - nearest hotel: No hotel found
hilo - nearest hotel: No hotel found
banda - nearest hotel: No hotel found
nalut - nearest hotel: No hotel found
makakilo city - nearest hotel: No hotel found
puerto del rosario - nearest hotel: No hotel found
kahului - nearest hotel: No hotel found
gat - nearest hotel: No hotel found
laguna - nearest hotel: No hotel found
tikaitnagar - nearest hotel: No hotel found
comodoro rivadavia - nearest hotel: No hotel found
san quintin - nearest hotel: No hotel found
santa rosalia - nearest hotel: No hotel found
pemba - nearest hotel: No hotel found
narwar - nearest hotel: No hotel found
port hedland - nearest hotel: No hotel found
roebourne - nearest hotel: No hotel found
saint-francois - nearest hotel: No hotel found
capoterra - nearest hotel: No hotel found
stolac - nearest hotel: No hotel found
guerrero negro - nearest hotel: No hotel found
bandarbeyla - nearest hotel: No hotel found

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
9,9,saint-pierre,-21.3393,55.4781,22.82,68,0,5.14,RE,1666108236,No hotel found
45,45,kapaa,22.0752,-159.3190,22.99,84,0,3.60,US,1666108257,No hotel found
51,51,hilo,19.7297,-155.0900,26.27,83,0,2.57,US,1666108260,No hotel found
63,63,banda,25.4833,80.3333,24.62,52,0,2.68,IN,1666108268,No hotel found
73,73,nalut,30.3333,10.8500,25.41,27,0,5.11,LY,1666108275,No hotel found
81,81,makakilo city,21.3469,-158.0858,21.66,81,0,2.57,US,1666108282,No hotel found
146,146,puerto del rosario,28.5004,-13.8627,24.86,73,0,4.63,ES,1666108035,No hotel found
152,152,kahului,20.8947,-156.4700,23.80,60,0,3.09,US,1666108246,No hotel found
197,197,gat,31.6100,34.7642,24.38,100,0,3.69,IL,1666108356,No hotel found
211,211,laguna,38.4210,-121.4238,21.67,79,0,2.06,US,1666108364,No hotel found
240,240,tikaitnagar,26.9500,81.5833,23.56,59,0,0.35,IN,1666108378,No hotel found
258,258,comodoro rivadavia,-45.8667,-67.5000,25.92,24,0,7.20,AR,1666108389,No hotel found
265,265,san quintin,30.4833,-115.9500,21.20,74,0,1.37,MX,1666108394,No hotel found
340,340,santa rosalia,27.3167,-112.2833,24.62,56,0,0.74,MX,1666108436,No hotel found
356,356,pemba,-12.9740,40.5178,25.03,76,0,6.33,MZ,1666108444,No hotel found
363,363,narwar,25.6500,77.9000,22.35,55,0,1.29,IN,1666108449,No hotel found
375,375,port hedland,-20.3167,118.5667,21.03,73,0,3.09,AU,1666108455,No hotel found
381,381,roebourne,-20.7833,117.1333,23.48,65,0,2.95,AU,1666108458,No hotel found
391,391,saint-francois,46.4154,3.9054,23.69,57,0,4.12,FR,1666108465,No hotel found
409,409,capoterra,39.1763,8.9718,24.84,71,0,3.60,IT,1666108477,No hotel found
421,421,stolac,43.0844,17.9575,24.88,68,0,0.80,BA,1666108483,No hotel found
516,516,guerrero negro,27.9769,-114.0611,23.17,68,0,0.89,MX,1666108537,No hotel found
517,517,bandarbeyla,9.4942,50.8122,25.88,81,0,5.14,SO,1666108537,No hotel found

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [9]:
%%capture --no-display

# Configure the map plot

info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""

hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]


locations = hotel_df[["Lat", "Lng"]]
weights = hotel_df['Humidity']
fig = gmaps.figure(center=(20.0, 0.0), zoom_level=2)
fig.add_layer(gmaps.heatmap_layer(locations, weights=weights))

# Assign the marker layer to a variable
markers = gmaps.marker_layer(locations)

# Add the layer to the map
fig.add_layer(markers)

# Display the map

fig

AttributeError: module 'collections' has no attribute 'Iterable'